### ISSUE TITLE
Clarification regarding confusion matrix

### ISSUE THREAD

**Issue by codedev99** [borarak/emotion-recognition-vgg13#1]
Hey! Awesome project btw, thanks for sharing.

I wanted to know what formula did you use while calculating values for the confusion matrix. My understanding is that when you take either a row or column, and sum the values, it should total to a hundred.

Example, a 0th row shows the images that were actually labelled neutral, and each value in that row specifies what percentage of these images were classified by the network as happy, sad, angry, etc. So the sum should be 100%, right?

Some clarification would be deeply appreciated, as I want to compare this with my model's performance as well, thanks.

**Comment by borarak** [comment]
iirc, the numbers are rounded off to display concisely

**Comment by codedev99** [comment]
ok, thanks for replying
